version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  event-service:
    build: ./event4you
    container_name: event-service
    depends_on:
      - mongodb
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/eventdb

  ticket-service:
    build: ./ticket4you
    container_name: ticket-service
    depends_on:
      - mongodb
      - event-service
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/ticketdb

volumes:
  mongo_data:
